language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - PACKAGES="django==1.4.13 django-mptt==0.5.5"   # django-polymorphic >= 0.5 uses django.utils.six which is bundled as of Django 1.4.2
  - PACKAGES="django==1.5.8"
  - PACKAGES="django==1.6.5"
install:
  - pip install -q $PACKAGES
  - pip install -q -e .
script:
  - python runtests.py
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-fluent"
    template:
      - "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
    skip_join: true
  email:
    recipients:
      - travis@edoburu.nl
    on_success: never
    on_failure: always
matrix:
  exclude:
    - python: "3.3"
      env: PACKAGES="django==1.4.13 django-mptt==0.5.5"
