language: python
sudo: false
cache: pip
python:
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - PACKAGES="django==1.5.8 django-mptt<0.7.0"
  - PACKAGES="django==1.6.5 django-mptt<0.8.0"
  - PACKAGES="django==1.7.1"
  - PACKAGES="django==1.8"
matrix:
  exclude:
  - python: "2.6"
    env: PACKAGES="django==1.7.1"
  - python: "2.6"
    env: PACKAGES="django==1.8"

before_install:
  - pip install codecov
install:
  - pip install -U pip wheel
  - pip install -q $PACKAGES
  - pip install -q -e .
script:
  - coverage run --source=fluent_pages runtests.py
after_success:
  - codecov

branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-fluent"
    template:
      - "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
    skip_join: true
  email:
    recipients:
      - travis@edoburu.nl
    on_success: never
    on_failure: always
